//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Chats = new HashSet<Chat>();
            this.Chats1 = new HashSet<Chat>();
            this.SendFiles = new HashSet<SendFile>();
            this.SendFiles1 = new HashSet<SendFile>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string UserDetails { get; set; }
        public string SessionKey { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<Chat> Chats1 { get; set; }
        public virtual ICollection<SendFile> SendFiles { get; set; }
        public virtual ICollection<SendFile> SendFiles1 { get; set; }
    }
}
