//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringConsumer.Console.ServiceReferenceString {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceString.IServiceString")]
    public interface IServiceString {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceString/NumberOfOccurences", ReplyAction="http://tempuri.org/IServiceString/NumberOfOccurencesResponse")]
        int NumberOfOccurences(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceString/NumberOfOccurences", ReplyAction="http://tempuri.org/IServiceString/NumberOfOccurencesResponse")]
        System.Threading.Tasks.Task<int> NumberOfOccurencesAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStringChannel : StringConsumer.Console.ServiceReferenceString.IServiceString, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStringClient : System.ServiceModel.ClientBase<StringConsumer.Console.ServiceReferenceString.IServiceString>, StringConsumer.Console.ServiceReferenceString.IServiceString {
        
        public ServiceStringClient() {
        }
        
        public ServiceStringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NumberOfOccurences(string first, string second) {
            return base.Channel.NumberOfOccurences(first, second);
        }
        
        public System.Threading.Tasks.Task<int> NumberOfOccurencesAsync(string first, string second) {
            return base.Channel.NumberOfOccurencesAsync(first, second);
        }
    }
}
