//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int NewEmployeeID { get; set; }
        public Nullable<System.DateTime> NewOnDate { get; set; }
        public string NewTask { get; set; }
        public Nullable<int> NewHoursWorked { get; set; }
        public string NewComments { get; set; }
    }
}
