//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLStudents.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Tutor { get; set; }
        public Nullable<double> Score { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
