//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLStudents.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Exams = new HashSet<Exam>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string eMail { get; set; }
        public int Course { get; set; }
        public string Specialty { get; set; }
        public int FacultyNumber { get; set; }
    
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
